# Generated by Django 6.0.5 on 2026-05-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vendoraccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vendor_access_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
