# Generated by Django 6.0.5 on 2026-05-18 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_gallerylike_vote_type_postlike_vote_type_bookmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to='message_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='view_once',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accepted_terms_ip',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('profile_update', 'Profile Updated'), ('new_post', 'New Forum Post'), ('new_gallery', 'New Gallery Upload'), ('content_flag', 'Content Flagged')], max_length=20),
        ),
        migrations.CreateModel(
            name='ContentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=30)),
                ('content_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('profanity', 'Profanity / Vulgar Language'), ('violence', 'Violent Content'), ('hate_speech', 'Hate Speech'), ('spam', 'Spam'), ('other', 'Other')], max_length=30)),
                ('flagged_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('auto_moderated', 'Auto-Moderated'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(default='login', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ip_user_id_d55b9a_idx'), models.Index(fields=['ip_hash'], name='accounts_ip_ip_hash_2aa48a_idx')],
            },
        ),
    ]
