# Generated by Django 6.0.5 on 2026-05-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_message_image_message_view_once_message_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_trial_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
