# Generated by Django 6.0.5 on 2026-05-19 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_premium_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_grace_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('profile_update', 'Profile Updated'), ('new_post', 'New Forum Post'), ('new_gallery', 'New Gallery Upload'), ('content_flag', 'Content Flagged'), ('premium_activated', 'Premium Activated'), ('premium_expiring', 'Premium Expiring'), ('premium_expired', 'Premium Expired')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card')], max_length=10)),
                ('mpesa_phone', models.CharField(blank=True, max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
