# Generated by Django 6.0.5 on 2026-05-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_views_publicly',
            field=models.BooleanField(default=True),
        ),
    ]
