# Generated by Django 6.0.5 on 2026-05-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_premium_trial_used_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE accounts_profile ALTER COLUMN phone DROP NOT NULL',
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE accounts_profile SET phone = NULL WHERE phone = ''",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            'UPDATE accounts_profile SET phone = NULL WHERE phone IN (SELECT phone FROM accounts_profile WHERE phone IS NOT NULL GROUP BY phone HAVING COUNT(*) > 1)',
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
