# Generated by Django 6.0.5 on 2026-05-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_group_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.IntegerField(default=100),
        ),
    ]
