# Generated by Django 6.0.5 on 2026-05-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_group_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messaging_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
