# Generated by Django 6.0.5 on 2026-05-20 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoraccesscode',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('gym_owner', 'Gym Owner'), ('coach', 'Coach')], default='vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='vendoraccesscode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_access_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
