# Generated by Django 6.0.5 on 2026-05-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_vendoraccesscode_role_vendoraccesscode_used_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('profile_update', 'Profile Updated'), ('new_post', 'New Forum Post'), ('new_gallery', 'New Gallery Upload'), ('content_flag', 'Content Flagged'), ('premium_activated', 'Premium Activated'), ('premium_expiring', 'Premium Expiring'), ('premium_expired', 'Premium Expired'), ('access_code_sent', 'Access Code Sent')], max_length=20),
        ),
    ]
