# Generated by Django 6.0.5 on 2026-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messaging_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
