# Generated by Django 6.0.5 on 2026-05-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_profile_messaging_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
