# Generated by Django 6.0.5 on 2026-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_groupmember_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
