services:
  backend:
    build: ./backend
    image: combathub-backend
    env_file: ./backend/.env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,yourdomain.com
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: combathub-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=capstone
      - POSTGRES_USER=levi
      - POSTGRES_PASSWORD=2962
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U levi -d capstone"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
