# Generated by Django 6.0.5 on 2026-05-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mpesa_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'MPesa'), ('visa', 'Visa')], max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='visa_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
