# Generated by Django 6.0.5 on 2026-05-18 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_mpesa_phone_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('publish_product', 'Can publish product'), ('manage_inventory', 'Can manage inventory')]},
        ),
    ]
