# Generated by Django 6.0.5 on 2026-05-23 08:52

from django.db import migrations, models


def backfill_serial_numbers(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.filter(serial_number='').iterator():
        if product.vendor_id:
            vendor_prefix = f"CS-{product.vendor_id:04d}"
            last_product = Product.objects.filter(
                vendor_id=product.vendor_id,
                serial_number__startswith=vendor_prefix,
            ).exclude(id=product.id).order_by('id').last()
            if last_product and last_product.serial_number:
                try:
                    last_seq = int(last_product.serial_number.split('-')[-1])
                    product.serial_number = f"{vendor_prefix}-{last_seq + 1:04d}"
                except (ValueError, IndexError):
                    product.serial_number = f"{vendor_prefix}-{product.id:04d}"
            else:
                product.serial_number = f"{vendor_prefix}-{product.id:04d}"
        else:
            product.serial_number = f"CS-0000-{product.id:04d}"
        product.save(update_fields=['serial_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_options'),
    ]

    operations = [
        migrations.RunPython(backfill_serial_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
