# Generated by Django 6.0.5 on 2026-05-24 12:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('interval', models.CharField(blank=True, choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=10)),
                ('max_products', models.IntegerField(default=5)),
                ('max_images_per_product', models.IntegerField(default=3)),
                ('discounts_allowed', models.BooleanField(default=False)),
                ('analytics_available', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vendor Premium Plan',
                'verbose_name_plural': 'Vendor Premium Plans',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='shop.vendorpremiumplan')),
                ('vendor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='shop.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Subscription',
                'verbose_name_plural': 'Vendor Subscriptions',
            },
        ),
    ]
