# Generated by Django 6.0.5 on 2026-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_vendorpremiumplan_vendorsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_avatars/'),
        ),
    ]
